import type {
  ChecklistItem,
  Competitor,
  Decision,
  EvidenceItem,
  EventTaxonomyItem,
  Experiment,
  Feature,
  IntegrationCheck,
  JourneyStep,
  LaunchAsset,
  Persona,
  ProductEvent,
  Risk,
  Task,
  WorkspaceState,
} from './types'

const now = new Date().toISOString()

export const personas: Persona[] = [
  {
    id: 'solo-builder',
    name: 'Mira',
    role: 'Solo product builder',
    need: 'Turn a fuzzy idea into a judged, shipped product without losing the thread.',
    anxiety: 'Shipping something that looks busy but does not solve a real problem.',
  },
  {
    id: 'product-lead',
    name: 'Dev',
    role: 'Product lead',
    need: 'See whether a build is strategically clear, measurable, and ready for strangers.',
    anxiety: 'A team spends the month building but cannot explain the product crisply.',
  },
  {
    id: 'hackathon-judge',
    name: 'Rae',
    role: 'Hackathon judge',
    need: 'Understand the user, workflow, ambition, and shipped evidence in minutes.',
    anxiety: 'A demo hides broken flows or does not include instrumentation.',
  },
]

export const features: Feature[] = [
  {
    id: 'judge-score',
    title: 'Judge-weighted readiness scoring',
    category: 'Strategy',
    description: 'Scores product thinking, execution, ambition, and shippedness with visible reasons.',
    impact: 10,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'product-thesis',
    title: 'Product thesis canvas',
    category: 'Strategy',
    description: 'Editable brief fields for audience, problem, solution, edge, and north star.',
    impact: 9,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'persona-lens',
    title: 'Persona lens switcher',
    category: 'Strategy',
    description: 'Keeps the experience anchored to a real user and their anxiety.',
    impact: 8,
    effort: 2,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'evidence-bank',
    title: 'Problem evidence bank',
    category: 'Strategy',
    description: 'Captures the proof that the problem is worth solving.',
    impact: 8,
    effort: 4,
    confidence: 8,
    status: 'building',
  },
  {
    id: 'differentiator',
    title: 'Differentiator stress test',
    category: 'Strategy',
    description: 'Forces a sharp answer to why this product deserves to exist now.',
    impact: 9,
    effort: 3,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'north-star',
    title: 'North star KPI designer',
    category: 'Strategy',
    description: 'Connects the product promise to one measurable behavior.',
    impact: 9,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'rice',
    title: 'RICE priority matrix',
    category: 'Build',
    description: 'Ranks features using impact, effort, and confidence so scope stays intentional.',
    impact: 10,
    effort: 5,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'scope-firewall',
    title: 'Scope firewall',
    category: 'Build',
    description: 'Keeps ambition high while making tradeoffs explicit.',
    impact: 8,
    effort: 3,
    confidence: 8,
    status: 'building',
  },
  {
    id: 'feature-status',
    title: 'Feature status toggles',
    category: 'Build',
    description: 'Moves each capability from planned to building to live.',
    impact: 8,
    effort: 2,
    confidence: 10,
    status: 'live',
  },
  {
    id: 'release-plan',
    title: '30-day release plan',
    category: 'Build',
    description: 'Turns the vision into sequenced work with dates and owners.',
    impact: 9,
    effort: 5,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'kanban',
    title: 'Launch kanban',
    category: 'Build',
    description: 'Tracks queued, active, and done launch work in one board.',
    impact: 8,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'milestones',
    title: 'Milestone burndown',
    category: 'Build',
    description: 'Shows whether the build is moving toward a real deadline.',
    impact: 7,
    effort: 4,
    confidence: 8,
    status: 'building',
  },
  {
    id: 'risk-radar',
    title: 'Risk radar',
    category: 'Build',
    description: 'Surfaces high-risk gaps before judges find them.',
    impact: 9,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'mitigation-map',
    title: 'Mitigation owner map',
    category: 'Build',
    description: 'Pairs each risk with a mitigation and resolved state.',
    impact: 7,
    effort: 3,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'experiment-backlog',
    title: 'Experiment backlog',
    category: 'Product',
    description: 'Defines learning loops with hypothesis, metric, audience, and status.',
    impact: 9,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'hypothesis-builder',
    title: 'Hypothesis designer',
    category: 'Product',
    description: 'Frames product bets as testable claims instead of vague opinions.',
    impact: 8,
    effort: 4,
    confidence: 8,
    status: 'building',
  },
  {
    id: 'metric-map',
    title: 'Success metric assignment',
    category: 'Product',
    description: 'Connects experiments to concrete usage and outcome metrics.',
    impact: 9,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'novus-guide',
    title: 'Novus integration guide',
    category: 'Analytics',
    description: 'Documents the install key path, visitor IDs, account IDs, and tracked events.',
    impact: 10,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'event-taxonomy',
    title: 'Event taxonomy',
    category: 'Analytics',
    description: 'Defines the events that matter for judging, learning, and launch iteration.',
    impact: 10,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'local-event-feed',
    title: 'Real-time local event feed',
    category: 'Analytics',
    description: 'Records product actions instantly even before the production Novus key is added.',
    impact: 9,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'funnel',
    title: 'Funnel health chart',
    category: 'Analytics',
    description: 'Visualizes the path from landing to launch-ready export.',
    impact: 8,
    effort: 5,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'adoption-trend',
    title: 'Adoption trend chart',
    category: 'Analytics',
    description: 'Shows whether usage behavior is strengthening over time.',
    impact: 7,
    effort: 5,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'retention-signal',
    title: 'Retention signal chart',
    category: 'Analytics',
    description: 'Gives a compact view of repeat product activity.',
    impact: 7,
    effort: 5,
    confidence: 8,
    status: 'building',
  },
  {
    id: 'submission-checklist',
    title: 'Submission checklist',
    category: 'Launch',
    description: 'Tracks public URL, demo video, Novus screenshot, description, and access notes.',
    impact: 10,
    effort: 3,
    confidence: 10,
    status: 'live',
  },
  {
    id: 'demo-script',
    title: 'Two-minute demo script builder',
    category: 'Launch',
    description: 'Generates a concise walkthrough aligned to the judging criteria.',
    impact: 9,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'devpost-copy',
    title: 'Submission description builder',
    category: 'Launch',
    description: 'Creates a ready-to-edit written description from the product workspace.',
    impact: 9,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'deployment-qa',
    title: 'Deployment QA checklist',
    category: 'Launch',
    description: 'Checks build, routes, mobile layout, browser console, and judging access.',
    impact: 10,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'accessibility-qa',
    title: 'Accessibility QA checklist',
    category: 'Launch',
    description: 'Keeps keyboard, labels, contrast, and responsive states visible.',
    impact: 8,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'privacy-qa',
    title: 'Security and privacy checklist',
    category: 'Launch',
    description: 'Prevents risky collection, unclear consent, and accidental secret exposure.',
    impact: 8,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'export-import',
    title: 'Workspace import and export',
    category: 'System',
    description: 'Downloads a complete launch workspace and restores it from JSON.',
    impact: 8,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'local-persistence',
    title: 'Local persistence',
    category: 'System',
    description: 'Saves edits automatically in the browser for uninterrupted work.',
    impact: 8,
    effort: 3,
    confidence: 10,
    status: 'live',
  },
  {
    id: 'keyboard-shortcuts',
    title: 'Keyboard navigation',
    category: 'System',
    description: 'Provides quick access to each product surface using number keys.',
    impact: 6,
    effort: 3,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'theme',
    title: 'Theme switcher',
    category: 'System',
    description: 'Supports bright and dark work sessions without losing visual hierarchy.',
    impact: 6,
    effort: 2,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'activity-log',
    title: 'Activity log',
    category: 'System',
    description: 'Creates a trace of meaningful product actions and launch events.',
    impact: 7,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'decision-log',
    title: 'Decision log',
    category: 'Product',
    description: 'Captures the why behind priority and launch tradeoffs.',
    impact: 7,
    effort: 3,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'confidence-forecast',
    title: 'Launch confidence forecast',
    category: 'Launch',
    description: 'Combines scope, risks, QA, and submission readiness into one forecast.',
    impact: 9,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'launch-coach',
    title: 'Launch coach recommendations',
    category: 'Product',
    description: 'Calculates the next best action from the weakest judging signal.',
    impact: 10,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'evidence-score',
    title: 'Evidence strength scoring',
    category: 'Strategy',
    description: 'Turns problem proof into a visible strength score instead of vague conviction.',
    impact: 9,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'competitor-wedge',
    title: 'Competitive wedge map',
    category: 'Strategy',
    description: 'Clarifies what existing tools miss and where LaunchPilot is meaningfully different.',
    impact: 8,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'judge-simulator',
    title: 'Judge simulator',
    category: 'Product',
    description: 'Shows how a judge is likely to read the product across all four criteria.',
    impact: 10,
    effort: 5,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'journey-map',
    title: 'Instrumented user journey map',
    category: 'Analytics',
    description: 'Connects user workflow steps to the exact analytics events judges can verify.',
    impact: 10,
    effort: 5,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'novus-health',
    title: 'Novus health diagnostics',
    category: 'Analytics',
    description: 'Reports whether the key is configured, the agent is loaded, and events are queued or sent.',
    impact: 10,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'event-queue',
    title: 'Analytics event queue',
    category: 'Analytics',
    description: 'Queues events while the Novus agent loads, then flushes them when tracking is available.',
    impact: 9,
    effort: 5,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'launch-assets',
    title: 'Launch asset studio',
    category: 'Launch',
    description: 'Tracks demo, Devpost, LinkedIn, testing, and support assets from draft to sent.',
    impact: 9,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'testing-instructions',
    title: 'Testing instructions generator',
    category: 'Launch',
    description: 'Creates clear judging access instructions from the live workspace.',
    impact: 9,
    effort: 3,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'deployment-proof',
    title: 'Deployment proof center',
    category: 'Launch',
    description: 'Separates local build confidence from public URL and Novus screenshot readiness.',
    impact: 10,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
  {
    id: 'score-delta',
    title: 'Score improvement path',
    category: 'Product',
    description: 'Ranks recommendations by score impact so progress stays accurate and focused.',
    impact: 9,
    effort: 4,
    confidence: 9,
    status: 'live',
  },
  {
    id: 'winner-brief',
    title: 'Winner narrative builder',
    category: 'Launch',
    description: 'Turns product data into a crisp story for judges and public launch posts.',
    impact: 8,
    effort: 4,
    confidence: 8,
    status: 'live',
  },
]

export const tasks: Task[] = [
  {
    id: 'brief',
    title: 'Lock the product thesis and target user',
    lane: 'Product',
    owner: 'Builder',
    due: 'Jun 06',
    status: 'done',
  },
  {
    id: 'flow',
    title: 'Design the first-use workflow around actual value',
    lane: 'UX',
    owner: 'Builder',
    due: 'Jun 08',
    status: 'done',
  },
  {
    id: 'scoring',
    title: 'Implement judge-aligned scoring engine',
    lane: 'Engineering',
    owner: 'Builder',
    due: 'Jun 09',
    status: 'active',
  },
  {
    id: 'analytics',
    title: 'Instrument event taxonomy and Novus-ready calls',
    lane: 'Analytics',
    owner: 'Builder',
    due: 'Jun 10',
    status: 'active',
  },
  {
    id: 'submission',
    title: 'Generate demo script and submission copy',
    lane: 'Launch',
    owner: 'Builder',
    due: 'Jun 12',
    status: 'active',
  },
  {
    id: 'qa',
    title: 'Run build, lint, responsive, and console QA',
    lane: 'Quality',
    owner: 'Builder',
    due: 'Jun 14',
    status: 'queued',
  },
  {
    id: 'deploy',
    title: 'Deploy public URL and verify judging access',
    lane: 'Launch',
    owner: 'Builder',
    due: 'Jun 16',
    status: 'queued',
  },
  {
    id: 'novus-shot',
    title: 'Add real Novus key and capture dashboard screenshot',
    lane: 'Analytics',
    owner: 'Builder',
    due: 'Jun 18',
    status: 'queued',
  },
]

export const experiments: Experiment[] = [
  {
    id: 'activation',
    hypothesis: 'Builders who see a judge score in the first minute will complete more launch tasks.',
    metric: 'Activation: first checklist item completed',
    audience: 'Solo builders',
    status: 'running',
  },
  {
    id: 'analytics-proof',
    hypothesis: 'A visible event taxonomy increases confidence that Novus is installed correctly.',
    metric: 'Novus setup view to launch export',
    audience: 'Hackathon participants',
    status: 'draft',
  },
  {
    id: 'submission-speed',
    hypothesis: 'Generated submission copy reduces the time from finished build to Devpost draft.',
    metric: 'Submission pack copied',
    audience: 'Product teams',
    status: 'draft',
  },
]

export const risks: Risk[] = [
  {
    id: 'novus-key',
    title: 'Real Novus key is not added before deployment',
    level: 'High',
    mitigation: 'Use VITE_NOVUS_PUBLIC_APP_ID in production and verify the dashboard screenshot.',
    resolved: false,
  },
  {
    id: 'scope-creep',
    title: 'Too many features blur the core value',
    level: 'Medium',
    mitigation: 'Keep every feature tied to shipping, measuring, or submitting.',
    resolved: true,
  },
  {
    id: 'demo-drift',
    title: 'Demo video becomes a tour instead of proof',
    level: 'Medium',
    mitigation: 'Use the generated two-minute script and show live actions.',
    resolved: false,
  },
  {
    id: 'deployment',
    title: 'Public URL is not accessible to judges',
    level: 'High',
    mitigation: 'Deploy static build and test it in a clean browser session.',
    resolved: false,
  },
]

export const evidence: EvidenceItem[] = [
  {
    id: 'deadline-pressure',
    title: 'Hackathon teams ship under deadline pressure',
    source: 'World Product Day rules and judging criteria',
    insight:
      'The challenge explicitly rewards shippedness, measurable behavior, and real products that strangers can use.',
    strength: 94,
  },
  {
    id: 'analytics-gap',
    title: 'Instrumentation is a submission blocker',
    source: 'Required Novus install and dashboard screenshot',
    insight:
      'A strong product can become ineligible if analytics is not installed and verified before submission.',
    strength: 98,
  },
  {
    id: 'builder-confusion',
    title: 'AI builders still need product judgement',
    source: 'Observed workflow problem',
    insight:
      'AI tools make creation faster, but they do not automatically create a focused audience, proof, launch story, or measurement plan.',
    strength: 88,
  },
  {
    id: 'judge-time',
    title: 'Judges need fast evidence',
    source: 'Submission video limit and public URL requirement',
    insight:
      'A product must prove value quickly through working flows, coherent copy, and visible instrumentation.',
    strength: 91,
  },
]

export const competitors: Competitor[] = [
  {
    id: 'project-docs',
    name: 'Static launch docs',
    positioning: 'Helpful for planning and checklists.',
    weakness: 'They do not update readiness from real product actions.',
    opportunity: 'LaunchPilot turns each action into score, evidence, and measurable progress.',
  },
  {
    id: 'generic-kanban',
    name: 'Generic task boards',
    positioning: 'Good for tracking work items.',
    weakness: 'They do not understand judging criteria, analytics eligibility, or submission proof.',
    opportunity: 'LaunchPilot connects execution to product thinking, ambition, and shippedness.',
  },
  {
    id: 'analytics-tools',
    name: 'Standalone analytics tools',
    positioning: 'Strong once a product is already instrumented.',
    weakness: 'They do not help a builder decide what to build, ship, and submit.',
    opportunity: 'LaunchPilot bridges planning, instrumentation, and launch artifacts.',
  },
]

export const journey: JourneyStep[] = [
  {
    id: 'open-workspace',
    title: 'Open workspace',
    goal: 'Understand readiness and deadline immediately.',
    event: 'workspace_opened',
    instrumented: true,
  },
  {
    id: 'inspect-score',
    title: 'Inspect score',
    goal: 'Find the weakest judging criterion.',
    event: 'criteria_viewed',
    instrumented: true,
  },
  {
    id: 'advance-build',
    title: 'Advance build',
    goal: 'Move a feature or task toward live.',
    event: 'feature_status_changed',
    instrumented: true,
  },
  {
    id: 'reduce-risk',
    title: 'Reduce risk',
    goal: 'Resolve a blocker before submission.',
    event: 'risk_resolved',
    instrumented: true,
  },
  {
    id: 'prepare-submission',
    title: 'Prepare submission',
    goal: 'Copy or export launch materials.',
    event: 'submission_pack_copied',
    instrumented: true,
  },
  {
    id: 'export-proof',
    title: 'Export proof',
    goal: 'Create a portable record of the launch state.',
    event: 'workspace_exported',
    instrumented: true,
  },
]

export const launchAssets: LaunchAsset[] = [
  {
    id: 'demo-video',
    title: 'Demo video',
    channel: 'Devpost',
    copy: 'Two-minute walkthrough showing Command, Strategy, Build, Analytics, and Launch flows.',
    status: 'draft',
  },
  {
    id: 'devpost-description',
    title: 'Devpost description',
    channel: 'Devpost',
    copy: 'Clear description of user, problem, product, tools, learning, and Novus instrumentation.',
    status: 'ready',
  },
  {
    id: 'testing-instructions',
    title: 'Testing instructions',
    channel: 'Judges',
    copy: 'Open the public URL, use the workspace, fire analytics events, and inspect generated launch assets.',
    status: 'ready',
  },
  {
    id: 'novus-proof',
    title: 'Novus screenshot',
    channel: 'Eligibility',
    copy: 'Dashboard screenshot proving events from the deployed project are visible in Novus.',
    status: 'draft',
  },
  {
    id: 'linkedin-story',
    title: 'Build-in-public post',
    channel: 'LinkedIn',
    copy: 'Share the shipping journey, why the product exists, and what changed after instrumentation.',
    status: 'draft',
  },
]

export const integrationChecks: IntegrationCheck[] = [
  {
    id: 'env-key',
    label: 'Novus install key',
    detail: 'Set VITE_NOVUS_PUBLIC_APP_ID in the deployed environment.',
    status: 'warn',
  },
  {
    id: 'visitor-id',
    label: 'Stable visitor ID',
    detail: 'The app creates and reuses a browser-local visitor identifier.',
    status: 'pass',
  },
  {
    id: 'account-id',
    label: 'Workspace account ID',
    detail: 'The account ID is derived from the product workspace name.',
    status: 'pass',
  },
  {
    id: 'event-taxonomy',
    label: 'Event taxonomy',
    detail: 'Core product actions are mapped to named analytics events.',
    status: 'pass',
  },
  {
    id: 'dashboard-proof',
    label: 'Dashboard screenshot',
    detail: 'Required after the deployed app sends real Novus events.',
    status: 'warn',
  },
]

export const checklist: ChecklistItem[] = [
  { id: 'public-url', label: 'Public deployed URL is live and accessible', done: false },
  { id: 'demo-video', label: 'Demo video is under three minutes and public or unlisted', done: false },
  { id: 'novus-installed', label: 'Novus is installed on the deployed app', done: false },
  { id: 'novus-screenshot', label: 'Novus dashboard screenshot is captured', done: false },
  { id: 'description', label: 'Written description explains user, value, tools, and learning', done: true },
  { id: 'testing', label: 'Testing instructions and access notes are ready', done: true },
  { id: 'ownership', label: 'Project is original work created during the eligible window', done: true },
]

export const qaChecks: ChecklistItem[] = [
  { id: 'build', label: 'Production build completes without TypeScript errors', done: false },
  { id: 'lint', label: 'Lint passes or known warnings are explained', done: false },
  { id: 'mobile', label: 'Mobile viewport keeps controls readable and non-overlapping', done: false },
  { id: 'desktop', label: 'Desktop viewport has coherent hierarchy and scan paths', done: false },
  { id: 'keyboard', label: 'Keyboard navigation and visible focus states work', done: true },
  { id: 'console', label: 'Browser console is clean in production preview', done: false },
  { id: 'secrets', label: 'No private keys are committed to the repository', done: true },
]

export const eventTaxonomy: EventTaxonomyItem[] = [
  {
    id: 'workspace_opened',
    event: 'workspace_opened',
    trigger: 'App loaded',
    why: 'Measures basic reach and first-use access.',
    active: true,
  },
  {
    id: 'criteria_viewed',
    event: 'criteria_viewed',
    trigger: 'Readiness criteria inspected',
    why: 'Shows whether users are engaging with judge-aligned feedback.',
    active: true,
  },
  {
    id: 'feature_status_changed',
    event: 'feature_status_changed',
    trigger: 'Feature moved between planned, building, and live',
    why: 'Measures build momentum and scope completion.',
    active: true,
  },
  {
    id: 'task_advanced',
    event: 'task_advanced',
    trigger: 'Kanban task status changed',
    why: 'Tracks real progress toward shippedness.',
    active: true,
  },
  {
    id: 'risk_resolved',
    event: 'risk_resolved',
    trigger: 'Risk resolved state toggled',
    why: 'Shows whether the user is reducing launch risk.',
    active: true,
  },
  {
    id: 'submission_pack_copied',
    event: 'submission_pack_copied',
    trigger: 'Submission copy or demo script copied',
    why: 'Measures conversion from planning to actual submission preparation.',
    active: true,
  },
  {
    id: 'workspace_exported',
    event: 'workspace_exported',
    trigger: 'Workspace JSON downloaded',
    why: 'Indicates a finished or shareable launch state.',
    active: true,
  },
  {
    id: 'coach_recommendation_selected',
    event: 'coach_recommendation_selected',
    trigger: 'Launch coach recommendation clicked',
    why: 'Measures whether users follow the system-generated next best action.',
    active: true,
  },
  {
    id: 'evidence_strength_updated',
    event: 'evidence_strength_updated',
    trigger: 'Evidence confidence changed',
    why: 'Shows whether product thinking is being sharpened with proof.',
    active: true,
  },
  {
    id: 'journey_step_instrumented',
    event: 'journey_step_instrumented',
    trigger: 'Journey step mapped to analytics',
    why: 'Measures instrumentation coverage across the workflow.',
    active: true,
  },
  {
    id: 'launch_asset_status_changed',
    event: 'launch_asset_status_changed',
    trigger: 'Launch asset moved between draft, ready, and sent',
    why: 'Tracks real submission preparation progress.',
    active: true,
  },
]

export const events: ProductEvent[] = [
  {
    id: 'seed-open',
    event: 'workspace_opened',
    timestamp: now,
    detail: 'LaunchPilot workspace initialized',
    source: 'local',
  },
]

export const decisions: Decision[] = [
  {
    id: 'decision-product',
    decision: 'Build a launch command center for product builders instead of a generic portfolio app.',
    reason: 'It directly matches the hackathon promise that everyone can ship and gives Novus a meaningful role.',
    timestamp: now,
  },
]

export const defaultWorkspace: WorkspaceState = {
  brief: {
    name: 'LaunchPilot',
    tagline: 'The command center that turns a raw idea into a measurable, judge-ready shipped product.',
    audience: 'AI-era product builders, PMs, designers, and solo founders shipping under a deadline.',
    problem:
      'Builders now have powerful creation tools, but many still lose the product thread: unclear user, messy scope, weak measurement, and last-minute submission chaos.',
    solution:
      'LaunchPilot combines product thesis, judge scoring, feature prioritization, task execution, analytics readiness, and submission assets in one working workspace.',
    differentiator:
      'It treats shipping as a measurable product workflow, not a checklist. Every action feeds readiness, risk, analytics, and launch evidence.',
    northStar: 'Launch-ready workspaces exported with Novus instrumentation confirmed.',
    deploymentUrl: '',
  },
  personas,
  features,
  tasks,
  experiments,
  risks,
  evidence,
  competitors,
  journey,
  launchAssets,
  integrationChecks,
  checklist,
  eventTaxonomy,
  events,
  decisions,
  qaChecks,
  darkMode: false,
  activePersonaId: 'solo-builder',
  lastSavedAt: now,
}

function mergeById<T extends { id: string }>(base: T[], current?: T[]): T[] {
  if (!current) {
    return base
  }

  const currentMap = new Map(current.map((item) => [item.id, item]))
  const baseIds = new Set(base.map((item) => item.id))
  const mergedBase = base.map((item) => ({ ...item, ...currentMap.get(item.id) }))
  const customItems = current.filter((item) => !baseIds.has(item.id))

  return [...mergedBase, ...customItems]
}

export function normalizeWorkspace(input: WorkspaceState): WorkspaceState {
  return {
    ...defaultWorkspace,
    ...input,
    brief: {
      ...defaultWorkspace.brief,
      ...input.brief,
    },
    personas: mergeById(defaultWorkspace.personas, input.personas),
    features: mergeById(defaultWorkspace.features, input.features),
    tasks: mergeById(defaultWorkspace.tasks, input.tasks),
    experiments: mergeById(defaultWorkspace.experiments, input.experiments),
    risks: mergeById(defaultWorkspace.risks, input.risks),
    evidence: mergeById(defaultWorkspace.evidence, input.evidence),
    competitors: mergeById(defaultWorkspace.competitors, input.competitors),
    journey: mergeById(defaultWorkspace.journey, input.journey),
    launchAssets: mergeById(defaultWorkspace.launchAssets, input.launchAssets),
    integrationChecks: mergeById(defaultWorkspace.integrationChecks, input.integrationChecks),
    checklist: mergeById(defaultWorkspace.checklist, input.checklist),
    eventTaxonomy: mergeById(defaultWorkspace.eventTaxonomy, input.eventTaxonomy),
    events: input.events ?? defaultWorkspace.events,
    decisions: input.decisions ?? defaultWorkspace.decisions,
    qaChecks: mergeById(defaultWorkspace.qaChecks, input.qaChecks),
  }
}
